title: DeltaPrint # 
logo: "/images/logo.jpg?raw=true" #
description: > # your text below (remove <br> elements if you don't need line breaks)
  Affordable 3d printing service
  CAD design
  Part reverse enginering
  Rapid prototyping
  <br><br>
  11 pioneer road 6529 George, South Africa
  081 708 1189
  deltaprintza@gmail.com
  <br><br>
  <a href="https://www.facebook.com/profile.php?id=100091792903842">View Our Facebook Page Here!</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
